package org.apache.nifi.copilot.capability;

public enum ValidationIssueType {
    UNKNOWN_PROCESSOR_TYPE,
    UNKNOWN_CONTROLLER_SERVICE_TYPE,
    DUPLICATE_CONTROLLER_SERVICE_NAME,
    UNSUPPORTED_PROPERTY,
    INVALID_ALLOWABLE_VALUE,
    UNRESOLVED_CONTROLLER_SERVICE_REFERENCE,
    INCOMPATIBLE_CONTROLLER_SERVICE,
    MISSING_REQUIRED_PROPERTY,
    UNSUPPORTED_SCHEDULING_STRATEGY,
    INVALID_CONCURRENT_TASKS,
    INVALID_RELATIONSHIPS,
    UNSUPPORTED_RELATIONSHIP,
    INVALID_DELETION,
    INVALID_CONTROLLER_SERVICE_ACTION,
    OTHER
}
